hs.hotkey.bind({ "cmd", "shift" }, "b", function()
	hs.execute("/opt/homebrew/bin/SwitchAudioSource -n")
	local output = hs.execute("/opt/homebrew/bin/SwitchAudioSource -c")
	hs.alert.show("switch to " .. output)
end)
